### ISSUE TITLE
Ability to create a new todo

### ISSUE THREAD

**Issue by ro-savage** [ro-savage/te-piha-interview#6]
## Story
Ability to create a new todo

## Specs
- [ ] Can type todo into input field
- [ ] Pressing enter will save todo
- [ ] Add save button
- [ ] Clicking save button adds todo
- [ ] Field is cleared of previous state
